# Generated by Django 4.1.1 on 2022-09-19 01:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registros", "0006_auto_20200810_0916"),
    ]

    operations = [
        migrations.AddField(
            model_name="avaliações",
            name="co2",
            field=models.FloatField(default="0.00"),
        ),
        migrations.AddField(
            model_name="avaliações",
            name="humidity",
            field=models.FloatField(default="0.00"),
        ),
        migrations.AddField(
            model_name="avaliações", name="o3", field=models.FloatField(default="0.00"),
        ),
        migrations.AddField(
            model_name="avaliações",
            name="pm25",
            field=models.FloatField(default="0.00"),
        ),
        migrations.AddField(
            model_name="avaliações",
            name="temperature",
            field=models.FloatField(default="0.00"),
        ),
        migrations.AddField(
            model_name="avaliações",
            name="voc",
            field=models.FloatField(default="0.00"),
        ),
        migrations.AddField(
            model_name="empresas", name="co2", field=models.FloatField(default="0.00"),
        ),
        migrations.AddField(
            model_name="empresas",
            name="humidity",
            field=models.FloatField(default="0.00"),
        ),
        migrations.AddField(
            model_name="empresas",
            name="last_updated",
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="empresas", name="o3", field=models.FloatField(default="0.00"),
        ),
        migrations.AddField(
            model_name="empresas", name="pm25", field=models.FloatField(default="0.00"),
        ),
        migrations.AddField(
            model_name="empresas",
            name="temperature",
            field=models.FloatField(default="0.00"),
        ),
        migrations.AddField(
            model_name="empresas", name="voc", field=models.FloatField(default="0.00"),
        ),
    ]
