# Generated by Django 4.1.1 on 2022-11-21 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registros", "0007_avaliações_co2_avaliações_humidity_avaliações_o3_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="avaliações",
            name="co2",
            field=models.FloatField(default="0.00"),
        ),
        migrations.AddField(
            model_name="avaliações",
            name="pm10",
            field=models.FloatField(default="0.00"),
        ),
        migrations.AddField(
            model_name="empresas", name="co2", field=models.FloatField(default="0.00"),
        ),
        migrations.AddField(
            model_name="empresas", name="pm10", field=models.FloatField(default="0.00"),
        ),
    ]
