# Generated by Django 4.1.1 on 2022-11-27 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registros", "0008_avaliações_co2_avaliações_pm10_empresas_co2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuários",
            name="super",
            field=models.BooleanField(default=False),
        ),
    ]
